version: '2'
services:
  php:
    build: ./php
    volumes:
      - ./app:/var/www/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
